<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class KumpulanDiagnosaKeperawatanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::connection('mysql2')->table('m_daftar_diagnosa_keperawatan')->insert([
            ['kode' => 'D.0001', 'diagnosa_keperawatan' => 'Bersihan jalan nafas tidak efektif'],
            ['kode' => 'D.0002', 'diagnosa_keperawatan' => 'Gangguan penyapihan ventilator'],
            ['kode' => 'D.0003', 'diagnosa_keperawatan' => 'Gangguan pertukaran gas'],
            ['kode' => 'D.0004', 'diagnosa_keperawatan' => 'Gangguan ventilasi spontan'],
            ['kode' => 'D.0005', 'diagnosa_keperawatan' => 'Pola nafas tidak efektif'],
            ['kode' => 'D.0006', 'diagnosa_keperawatan' => 'Resiko aspirasi'],
            ['kode' => 'D.0007', 'diagnosa_keperawatan' => 'Gangguan sirkulasi spontan'],
            ['kode' => 'D.0008', 'diagnosa_keperawatan' => 'Penurunan curah jantung'],
            ['kode' => 'D.0009', 'diagnosa_keperawatan' => 'Perfusi perifer tidak efektif'],
            ['kode' => 'D.0010', 'diagnosa_keperawatan' => 'Risiko gangguan sirkulasi spontan'],
            ['kode' => 'D.0011', 'diagnosa_keperawatan' => 'Risiko penurunan curah jantung'],
            ['kode' => 'D.0012', 'diagnosa_keperawatan' => 'Risiko perdarahan'],
            ['kode' => 'D.0013', 'diagnosa_keperawatan' => 'Risiko perfusi gastrointestinal tidak efektif'],
            ['kode' => 'D.0014', 'diagnosa_keperawatan' => 'Risiko perfusi perifer miokard tidak efektif'],
            ['kode' => 'D.0015', 'diagnosa_keperawatan' => 'Risiko perfusi perifer tidak efektif'],
            ['kode' => 'D.0016', 'diagnosa_keperawatan' => 'Resiko perfusi renal tidak efektif'],
            ['kode' => 'D.0017', 'diagnosa_keperawatan' => 'Resiko perfusi serebral tidak efektif'],
            ['kode' => 'D.0018', 'diagnosa_keperawatan' => 'Berat badan lebih'],
            ['kode' => 'D.0019', 'diagnosa_keperawatan' => 'Defisit nutrisi'],
            ['kode' => 'D.0020', 'diagnosa_keperawatan' => 'Diare'],
            ['kode' => 'D.0021', 'diagnosa_keperawatan' => 'Disfungsi motilitas gastrointestinal'],
            ['kode' => 'D.0022', 'diagnosa_keperawatan' => 'Hipervolemia'],
            ['kode' => 'D.0023', 'diagnosa_keperawatan' => 'Hipovolemi'],
            ['kode' => 'D.0024', 'diagnosa_keperawatan' => 'Ikterik neonatus'],
            ['kode' => 'D.0025', 'diagnosa_keperawatan' => 'Kesiapan peningkatan keseimbangan cairan'],
            ['kode' => 'D.0026', 'diagnosa_keperawatan' => 'Kesiapan peningkatan nutrisi'],
            ['kode' => 'D.0027', 'diagnosa_keperawatan' => 'Ketidakstabilan kadar glukosa darah'],
            ['kode' => 'D.0028', 'diagnosa_keperawatan' => 'Menyusi efektif'],
            ['kode' => 'D.0029', 'diagnosa_keperawatan' => 'Menyusui tidak efektif'],
            ['kode' => 'D.0030', 'diagnosa_keperawatan' => 'Obesitas'],
            ['kode' => 'D.0031', 'diagnosa_keperawatan' => 'Risiko berat badan lebih'],
            ['kode' => 'D.0032', 'diagnosa_keperawatan' => 'Defisit nutrisi'],
            ['kode' => 'D.0033', 'diagnosa_keperawatan' => 'Risiko disfungsi motilitas gastrointestinal'],
            ['kode' => 'D.0034', 'diagnosa_keperawatan' => 'Risiko hipovolemia'],
            ['kode' => 'D.0035', 'diagnosa_keperawatan' => 'Risiko ikterik neonatus'],
            ['kode' => 'D.0036', 'diagnosa_keperawatan' => 'Risiko ketidakseimbangan cairan'],
            ['kode' => 'D.0037', 'diagnosa_keperawatan' => 'Risiko ketidakseimbangan elektrolit'],
            ['kode' => 'D.0038', 'diagnosa_keperawatan' => 'Risiko ketidakstabilan kadar glukosa darah'],
            ['kode' => 'D.0039', 'diagnosa_keperawatan' => 'Risiko syock'],
            ['kode' => 'D.0040', 'diagnosa_keperawatan' => 'Gangguan eliminas urin'],
            ['kode' => 'D.0041', 'diagnosa_keperawatan' => 'Inkontensia fekal'],
            ['kode' => 'D.0042', 'diagnosa_keperawatan' => 'Inkontinensia urine berlanjut'],
            ['kode' => 'D.0043', 'diagnosa_keperawatan' => 'Inkontensia urine berlebih'],
            ['kode' => 'D.0044', 'diagnosa_keperawatan' => 'Inkontensia urine fungsional'],
            ['kode' => 'D.0045', 'diagnosa_keperawatan' => 'Inkontensia urin reflek'],
            ['kode' => 'D.0046', 'diagnosa_keperawatan' => 'Inkontensia urin stres'],
            ['kode' => 'D.0047', 'diagnosa_keperawatan' => 'Inkontensia urin urgensi'],
            ['kode' => 'D.0048', 'diagnosa_keperawatan' => 'Kesiapan peningkatan eliminasi urin'],
            ['kode' => 'D.0049', 'diagnosa_keperawatan' => 'Konstipasi'],
            ['kode' => 'D.0050', 'diagnosa_keperawatan' => 'Retensi urin'],
            ['kode' => 'D.0051', 'diagnosa_keperawatan' => 'risiko inkontensia urine urgensi'],
            ['kode' => 'D.0052', 'diagnosa_keperawatan' => 'Resiko konstipasi'],
            ['kode' => 'D.0053', 'diagnosa_keperawatan' => 'Disorganisasi perilaku bayi'],
            ['kode' => 'D.0054', 'diagnosa_keperawatan' => 'Gangguan mobilitas fisik'],
            ['kode' => 'D.0055', 'diagnosa_keperawatan' => 'Gangguan pola tidur'],
            ['kode' => 'D.0056', 'diagnosa_keperawatan' => 'Intoleransi aktivitas'],
            ['kode' => 'D.0057', 'diagnosa_keperawatan' => 'Keletihan'],
            ['kode' => 'D.0058', 'diagnosa_keperawatan' => 'Kesiapan peningkatan perilaku bayi'],
            ['kode' => 'D.0059', 'diagnosa_keperawatan' => 'Risiko Disorganisai perilaku bayi'],
            ['kode' => 'D.0060', 'diagnosa_keperawatan' => 'Risiko intoleransi aktivitas'],
            ['kode' => 'D.0061', 'diagnosa_keperawatan' => 'Disrefleksi otonom'],
            ['kode' => 'D.0062', 'diagnosa_keperawatan' => 'Gangguan Memori'],
            ['kode' => 'D.0063', 'diagnosa_keperawatan' => 'Gangguan menelan'],
            ['kode' => 'D.0064', 'diagnosa_keperawatan' => 'Konfusi akut'],
            ['kode' => 'D.0065', 'diagnosa_keperawatan' => 'Konfusi kronis'],
            ['kode' => 'D.0066', 'diagnosa_keperawatan' => 'Penurunan kapasitas adaptif'],
            ['kode' => 'D.0067', 'diagnosa_keperawatan' => 'Risiko disfungsi neurovaskuler perifer'],
            ['kode' => 'D.0068', 'diagnosa_keperawatan' => 'Risiko konfusi akut'],
            ['kode' => 'D.0069', 'diagnosa_keperawatan' => 'Disfungsi seksual'],
            ['kode' => 'D.0070', 'diagnosa_keperawatan' => 'Kesiapan Persalinan'],
            ['kode' => 'D.0071', 'diagnosa_keperawatan' => 'Pola seksual tidak efektif'],
            ['kode' => 'D.0072', 'diagnosa_keperawatan' => 'Risiko disfungsi seksual'],
            ['kode' => 'D.0073', 'diagnosa_keperawatan' => 'Risiko kehamilan tidak di kehendaki'],
            ['kode' => 'D.0074', 'diagnosa_keperawatan' => 'Gangguan rasa nyaman'],
            ['kode' => 'D.0075', 'diagnosa_keperawatan' => 'Ketidaknyamanan pasca partum'],
            ['kode' => 'D.0076', 'diagnosa_keperawatan' => 'Nausea'],
            ['kode' => 'D.0077', 'diagnosa_keperawatan' => 'Nyeri akut'],
            ['kode' => 'D.0078', 'diagnosa_keperawatan' => 'Nyeri kronis'],
            ['kode' => 'D.0079', 'diagnosa_keperawatan' => 'Nyeri melahirkan'],
            ['kode' => 'D.0080', 'diagnosa_keperawatan' => 'Ansietas'],
            ['kode' => 'D.0081', 'diagnosa_keperawatan' => 'Berduka'],
            ['kode' => 'D.0082', 'diagnosa_keperawatan' => 'Distress sipritual'],
            ['kode' => 'D.0083', 'diagnosa_keperawatan' => 'Gangguan citra tubuh'],
            ['kode' => 'D.0084', 'diagnosa_keperawatan' => 'Gangguan identitas diri'],
            ['kode' => 'D.0085', 'diagnosa_keperawatan' => 'Gangguan Persepsi Sensori'],
            ['kode' => 'D.0086', 'diagnosa_keperawatan' => 'Harga diri rendah kronis'],
            ['kode' => 'D.0087', 'diagnosa_keperawatan' => 'Harga diri rendah situasional'],
            ['kode' => 'D.0088', 'diagnosa_keperawatan' => 'Keputusasaan'],
            ['kode' => 'D.0089', 'diagnosa_keperawatan' => 'Kesiapan peningkatan konsep diri'],
            ['kode' => 'D.0090', 'diagnosa_keperawatan' => 'Kesiapan peningkatan koping keluarga'],
            ['kode' => 'D.0091', 'diagnosa_keperawatan' => 'Kesiapan peningkatan koping komunitas'],
            ['kode' => 'D.0092', 'diagnosa_keperawatan' => 'Ketidakberdayaan'],
            ['kode' => 'D.0093', 'diagnosa_keperawatan' => 'Ketidakmampuan koping keluarga'],
            ['kode' => 'D.0094', 'diagnosa_keperawatan' => 'Koping defensif'],
            ['kode' => 'D.0095', 'diagnosa_keperawatan' => 'Koping komunitas tidak efektif'],
            ['kode' => 'D.0096', 'diagnosa_keperawatan' => 'Koping tidak efektif'],
            ['kode' => 'D.0097', 'diagnosa_keperawatan' => 'Penurunan koping keluarga'],
            ['kode' => 'D.0098', 'diagnosa_keperawatan' => 'Penyangkalan'],
            ['kode' => 'D.0099', 'diagnosa_keperawatan' => 'Perilaku kesehatan cenderung beresiko'],
            ['kode' => 'D.0100', 'diagnosa_keperawatan' => 'Risiko distress spiritual'],
            ['kode' => 'D.0101', 'diagnosa_keperawatan' => 'Risiko harga diri rendah kronis'],
            ['kode' => 'D.0102', 'diagnosa_keperawatan' => 'Risiko harga diri rendah situasional'],
            ['kode' => 'D.0103', 'diagnosa_keperawatan' => 'Risiko ketidakberdayaan'],
            ['kode' => 'D.0104', 'diagnosa_keperawatan' => 'Sindrom pasca trauma'],
            ['kode' => 'D.0105', 'diagnosa_keperawatan' => 'Waham'],
            ['kode' => 'D.0106', 'diagnosa_keperawatan' => 'Gangguan tumbuh kembang'],
            ['kode' => 'D.0107', 'diagnosa_keperawatan' => 'Resiko gangguan perkembangan'],
            ['kode' => 'D.0108', 'diagnosa_keperawatan' => 'Risiko gangguan pertumbuhan'],
            ['kode' => 'D.0109', 'diagnosa_keperawatan' => 'Defisit perawatan diri'],
            ['kode' => 'D.0111', 'diagnosa_keperawatan' => 'Defisit pengetahuan'],
            ['kode' => 'D.0112', 'diagnosa_keperawatan' => 'Kesiapan peningkatan manajemen kesehatan'],
            ['kode' => 'D.0113', 'diagnosa_keperawatan' => 'Kesiapan peningkatan pengetahuan'],
            ['kode' => 'D.0114', 'diagnosa_keperawatan' => 'Ketidakpatuhan'],
            ['kode' => 'D.0115', 'diagnosa_keperawatan' => 'Manajemen kesehatan keluarga tidak efektif'],
            ['kode' => 'D.0116', 'diagnosa_keperawatan' => 'Manajemen kesehatan tidak efektif'],
            ['kode' => 'D.0117', 'diagnosa_keperawatan' => 'Pemeliharaan kesehatan tidak efektif'],
            ['kode' => 'D.0118', 'diagnosa_keperawatan' => 'Gangguan inteaksi sosial'],
            ['kode' => 'D.0119', 'diagnosa_keperawatan' => 'Gangguan komunikasi verbal'],
            ['kode' => 'D.0120', 'diagnosa_keperawatan' => 'Gangguan proses keluarga'],
            ['kode' => 'D.0121', 'diagnosa_keperawatan' => 'Isolasi sosial'],
            ['kode' => 'D.0122', 'diagnosa_keperawatan' => 'Kesiapan peningkatan menjadi orang tua'],
            ['kode' => 'D.0123', 'diagnosa_keperawatan' => 'Kesiapan peningkatan proses keluarga'],
            ['kode' => 'D.0124', 'diagnosa_keperawatan' => 'Ketegangan peran pemberi asuhan'],
            ['kode' => 'D.0125', 'diagnosa_keperawatan' => 'Penampilan peran tidak efektif'],
            ['kode' => 'D.0126', 'diagnosa_keperawatan' => 'Pencapaian peran menjadi orang tua'],
            ['kode' => 'D.0127', 'diagnosa_keperawatan' => 'Risiko gangguan perlekatan'],
            ['kode' => 'D.0128', 'diagnosa_keperawatan' => 'Risiko proses pengasuhan tidak efektif'],
            ['kode' => 'D.0129', 'diagnosa_keperawatan' => 'Gangguan integritas kulit jaringan'],
            ['kode' => 'D.0130', 'diagnosa_keperawatan' => 'Hipertermi'],
            ['kode' => 'D.0131', 'diagnosa_keperawatan' => 'Hipotermi'],
            ['kode' => 'D.0132', 'diagnosa_keperawatan' => 'Perilaku kekerasan'],
            ['kode' => 'D.0133', 'diagnosa_keperawatan' => 'Keterlambatan pemulihan pasca bedah'],
            ['kode' => 'D.0134', 'diagnosa_keperawatan' => 'Risiko alergi'],
            ['kode' => 'D.0135', 'diagnosa_keperawatan' => 'Risiko bunuh diri'],
            ['kode' => 'D.0136', 'diagnosa_keperawatan' => 'Risiko cedera'],
            ['kode' => 'D.0137', 'diagnosa_keperawatan' => 'Risiko cedera pada ibu'],
            ['kode' => 'D.0138', 'diagnosa_keperawatan' => 'Risiko cedera pada janin'],
            ['kode' => 'D.0139', 'diagnosa_keperawatan' => 'Risiko gangguan integritas kulit'],
            ['kode' => 'D.0140', 'diagnosa_keperawatan' => 'Risiko hipotermia'],
            ['kode' => 'D.0141', 'diagnosa_keperawatan' => 'Hipotermia perioperatif'],
            ['kode' => 'D.0142', 'diagnosa_keperawatan' => 'Risiko infeksi'],
            ['kode' => 'D.0143', 'diagnosa_keperawatan' => 'Risiko jatuh'],
            ['kode' => 'D.0144', 'diagnosa_keperawatan' => 'Risiko luka tekan'],
            ['kode' => 'D.0145', 'diagnosa_keperawatan' => 'Risiko mutilasi diri'],
            ['kode' => 'D.0146', 'diagnosa_keperawatan' => 'Risiko perilaku kekerasan'],
            ['kode' => 'D.0147', 'diagnosa_keperawatan' => 'Risiko perlambatan pemulihan pasca bedah'],
            ['kode' => 'D.0148', 'diagnosa_keperawatan' => 'Risiko termoregulasi tidak efektif'],
            ['kode' => 'D.0149', 'diagnosa_keperawatan' => 'Termoregulasi tidak efektif']
        ]);
    }
}
