<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class DropColumnRsEdukasiPasienTable extends Migration
{
    public function up()
    {
        Schema::table('rs_edukasi_pasien', function (Blueprint $table) {
            $table->dropColumn([
                'topik_dianogsa',
                'topik_penyakit',
                'topik_prosedur',
                'topik_manajemen_nyeri',
                'topik_lain_lain_dokter',
                'topik_peralatan_perawat',
                'topik_infeksi_perawat',
                'topik_nyeri_perawat',
                'topik_lain_lain_perawat',
                'topik_nutrisi_gizi',
                'topik_diet_gizi',
                'topik_lain_lain_gizi',
                'topik_obat_farmasi',
                'topik_efek_samping_farmasi',
                'topik_interaksi_obat_farmasi',
                'topik_lain_lain_farmasi',
                'topik_teknik_rehab',
                'topik_lain_lain_rehab',
                'tanggal_edukasi_diagnosa',
                'tanggal_edukasi_penyakit',
                'tanggal_edukasi_prosedur',
                'tanggal_edukasi_nyeri',
                'tanggal_edukasi_lain_lain',
                'tanggal_edukasi_peralatan_perawat',
                'tanggal_edukasi_infeksi_perawat',
                'tanggal_edukasi_nyeri_perawat',
                'tanggal_edukasi_lain_lain_perawat',
                'tanggal_edukasi_nutrisi_gizi',
                'tanggal_edukasi_diet_gizi',
                'tanggal_edukasi_lain_lain_gizi',
                'tanggal_edukasi_obat_farmasi',
                'tanggal_edukasi_efek_samping_farmasi',
                'tanggal_edukasi_interaksi_obat_farmasi',
                'tanggal_edukasi_lain_lain_farmasi',
                'tanggal_edukasi_teknik_rehab',
                'tanggal_edukasi_lain_lain_rehab',
                'tingkat_pemahaman_diagnosa',
                'tingkat_pemahaman_penyakit',
                'tingkat_pemahaman_prosedur',
                'tingkat_pemahaman_nyeri',
                'tingkat_pemahaman_lain_lain',
                'tingkat_pemahaman_peralatan_perawat',
                'tingkat_pemahaman_infeksi_perawat',
                'tingkat_pemahaman_nyeri_perawat',
                'tingkat_pemahaman_lain_lain_perawat',
                'tingkat_pemahaman_nutrisi_gizi',
                'tingkat_pemahaman_diet_gizi',
                'tingkat_pemahaman_lain_lain_gizi',
                'tingkat_pemahaman_obat_farmasi',
                'tingkat_pemahaman_efek_samping_farmasi',
                'tingkat_pemahaman_interaksi_obat_farmasi',
                'tingkat_pemahaman_lain_lain_farmasi',
                'tingkat_pemahaman_teknik_rehab',
                'tingkat_pemahaman_lain_lain_rehab',
                'metode_edukasi_diagnosa',
                'metode_edukasi_penyakit',
                'metode_edukasi_prosedur',
                'metode_edukasi_nyeri',
                'metode_edukasi_lain_lain',
                'metode_edukasi_peralatan_perawat',
                'metode_edukasi_infeksi_perawat',
                'metode_edukasi_nyeri_perawat',
                'metode_edukasi_lain_lain_perawat',
                'metode_edukasi_nutrisi_gizi',
                'metode_edukasi_diet_gizi',
                'metode_edukasi_lain_lain_gizi',
                'metode_edukasi_obat_farmasi',
                'metode_edukasi_efek_samping_farmasi',
                'metode_edukasi_interaksi_obat_farmasi',
                'metode_edukasi_lain_lain_farmasi',
                'metode_edukasi_teknik_rehab',
                'metode_edukasi_lain_lain_rehab',
            ]);
        });
    }

    public function down()
    {
        Schema::table('rs_edukasi_pasien', function (Blueprint $table) {
            $table->string('topik_dianogsa')->nullable();
            $table->string('topik_penyakit')->nullable();
            $table->string('topik_prosedur')->nullable();
            $table->string('topik_manajemen_nyeri')->nullable();
            $table->string('topik_lain_lain_dokter')->nullable();
            $table->string('topik_peralatan_perawat')->nullable();
            $table->string('topik_infeksi_perawat')->nullable();
            $table->string('topik_nyeri_perawat')->nullable();
            $table->string('topik_lain_lain_perawat')->nullable();
            $table->string('topik_nutrisi_gizi')->nullable();
            $table->string('topik_diet_gizi')->nullable();
            $table->string('topik_lain_lain_gizi')->nullable();
            $table->string('topik_obat_farmasi')->nullable();
            $table->string('topik_efek_samping_farmasi')->nullable();
            $table->string('topik_interaksi_obat_farmasi')->nullable();
            $table->string('topik_lain_lain_farmasi')->nullable();
            $table->string('topik_teknik_rehab')->nullable();
            $table->string('topik_lain_lain_rehab')->nullable();
            $table->date('tanggal_edukasi_diagnosa')->nullable();
            $table->date('tanggal_edukasi_penyakit')->nullable();
            $table->date('tanggal_edukasi_prosedur')->nullable();
            $table->date('tanggal_edukasi_nyeri')->nullable();
            $table->date('tanggal_edukasi_lain_lain')->nullable();
            $table->date('tanggal_edukasi_peralatan_perawat')->nullable();
            $table->date('tanggal_edukasi_infeksi_perawat')->nullable();
            $table->date('tanggal_edukasi_nyeri_perawat')->nullable();
            $table->date('tanggal_edukasi_lain_lain_perawat')->nullable();
            $table->date('tanggal_edukasi_nutrisi_gizi')->nullable();
            $table->date('tanggal_edukasi_diet_gizi')->nullable();
            $table->date('tanggal_edukasi_lain_lain_gizi')->nullable();
            $table->date('tanggal_edukasi_obat_farmasi')->nullable();
            $table->date('tanggal_edukasi_efek_samping_farmasi')->nullable();
            $table->date('tanggal_edukasi_interaksi_obat_farmasi')->nullable();
            $table->date('tanggal_edukasi_lain_lain_farmasi')->nullable();
            $table->date('tanggal_edukasi_teknik_rehab')->nullable();
            $table->date('tanggal_edukasi_lain_lain_rehab')->nullable();
            $table->string('tingkat_pemahaman_diagnosa')->nullable();
            $table->string('tingkat_pemahaman_penyakit')->nullable();
            $table->string('tingkat_pemahaman_prosedur')->nullable();
            $table->string('tingkat_pemahaman_nyeri')->nullable();
            $table->string('tingkat_pemahaman_lain_lain')->nullable();
            $table->string('tingkat_pemahaman_peralatan_perawat')->nullable();
            $table->string('tingkat_pemahaman_infeksi_perawat')->nullable();
            $table->string('tingkat_pemahaman_nyeri_perawat')->nullable();
            $table->string('tingkat_pemahaman_lain_lain_perawat')->nullable();
            $table->string('tingkat_pemahaman_nutrisi_gizi')->nullable();
            $table->string('tingkat_pemahaman_diet_gizi')->nullable();
            $table->string('tingkat_pemahaman_lain_lain_gizi')->nullable();
            $table->string('tingkat_pemahaman_obat_farmasi')->nullable();
            $table->string('tingkat_pemahaman_efek_samping_farmasi')->nullable();
            $table->string('tingkat_pemahaman_interaksi_obat_farmasi')->nullable();
            $table->string('tingkat_pemahaman_lain_lain_farmasi')->nullable();
            $table->string('tingkat_pemahaman_teknik_rehab')->nullable();
            $table->string('tingkat_pemahaman_lain_lain_rehab')->nullable();
            $table->string('metode_edukasi_diagnosa')->nullable();
            $table->string('metode_edukasi_penyakit')->nullable();
            $table->string('metode_edukasi_prosedur')->nullable();
            $table->string('metode_edukasi_nyeri')->nullable();
            $table->string('metode_edukasi_lain_lain')->nullable();
            $table->string('metode_edukasi_peralatan_perawat')->nullable();
            $table->string('metode_edukasi_infeksi_perawat')->nullable();
            $table->string('metode_edukasi_nyeri_perawat')->nullable();
            $table->string('metode_edukasi_lain_lain_perawat')->nullable();
            $table->string('metode_edukasi_nutrisi_gizi')->nullable();
            $table->string('metode_edukasi_diet_gizi')->nullable();
            $table->string('metode_edukasi_lain_lain_gizi')->nullable();
            $table->string('metode_edukasi_obat_farmasi')->nullable();
            $table->string('metode_edukasi_efek_samping_farmasi')->nullable();
            $table->string('metode_edukasi_interaksi_obat_farmasi')->nullable();
            $table->string('metode_edukasi_lain_lain_farmasi')->nullable();
            $table->string('metode_edukasi_teknik_rehab')->nullable();
            $table->string('metode_edukasi_lain_lain_rehab')->nullable();
        });
    }
}
