# SQLSERVER
# first connection
DB_CONNECTION=mysql
DB_HOST=192.168.80.114\DB_SERVER_RSUD
DB_PORT=
DB_DATABASE=rs_inap
DB_USERNAME=aset
DB_PASSWORD=aset@123???

DB_MASTER_CONNECTION=mysql2
DB_MASTER_HOST=192.168.80.114\DB_SERVER_RSUD
DB_MASTER_PORT=
DB_MASTER_DATABASE=rs_master
DB_MASTER_USERNAME=aset
DB_MASTER_PASSWORD=aset@123???